language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp bower
- bower install
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/warlockbrawl/warlockbrawl.com.git
  - secure: g/YuEu7vv2pmPTMWgt3d0rEXNwMQDqjZCD/fYjnKa66YMKQifDpVT4dfWH5aBAnw4jRbd7Uhw0XMChvBkbsuWBOmIp5c9atyh1nuGjdlYrO3vXDP4Qw/0QXwtyWDgKF75+j7nTzBbcVPhs/zqruS5KNy7YW5D2Ys6/1ku7SThP1GJRIPxNggYSO/EO/4irL3FwXkYPR+o9AtjHlFoyJBcBCex6+pDelBmYOYINHlIHIE5JEDhp22FhDbVNTep/sjh2S2brMU3KXNB/FoNFDInLXQbmRijZ4QSjU5CA2qlwRBBJFMXxqNNkHwm7RgcKNKkP/qvG5ASr9rF/b/zZEAWgO2dIhJSQhACJ0zG+6NNzf/augev8kUnqne/W8SEqm2ZBBIqF3yy8PQ+10b9I4BuG2b6n91jznMt7TOf5zSzK7rcnQj+5A3NF/Znbt5zOCjUD+06bpCRs10yGRW6eWmPHJ5JVWwRHoeKkWhoEdr6BtZcWdpwDEMSGF9KWMpPNuwdID0Q4CgBAiCpgRVPJRFYbJo5kQFHtVeCEdlXfLI/aj3Sv5mIfOAZf2uuJ7FE3KZuOvNlSyosSQB7EYHa+sDKeGXV21g6hcXnoqAroBAIU2BhU0MNjRXRu+jGAOO9/kDw8uZKUFCa3ZMXGSX0pDDmjY9c6eurJyCon+nnYFm3GE=

