language: node_js
node_js:
- '4.0'
branches:
  only:
  - master
before_script:
- npm install -g gulp bower
- bower install
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/warlockbrawl/warlockbrawl.github.io.git
  - GH_CNAME: latest.warlockbrawl.com
  - secure: VWAdgJT7IQziUfZd6oadd+hSnojH9FDSie6S0BdQ7FHtEKYO1gPf0FPbJavG4Bpjkzn47CNsAilJ6KzVB2T79uRw+xY91nyCmkj2HrwFC+ixVlVBUsF9CfUiZU+sf920t96dWNOLlaxgBRYsN6kck1knGv3JI6bOEIkCcKv+FMgnZ9kOyveRBBfb80UB2rgOm3IQEkJKhODIj1L70FooXYFZwW1guXVLDULFcr7Eqnj9g+bgyOxPEF4p9J+XPNZnW0kwdN6PNruwFBg3nsz0yScsJqsTaS6jVcga9WoZaFTHP+hSv8AfvL0xW6+ba7Tk4a9WqN8xbJQ+Sr4gmfFVVIEB5Bmo7GSGAQUZieqGe7/Vn6AfU/5aNme2lQoBzG5+a0X7JBGFSx9T/29/Dy0ZG0BtA/1ZjVlSwvQvXMCSWEcGZYwICsQm9HVkbCpJSPJfGNFwZgBgreTD9Aux061QcwfcFvk1w/Z6w9olQWNtwPayYzDn2oXd88hRMNf09dqHbzYkPuesNXu2aWFUN3bfE+WveaucrBaxB83vGa8pvULLivUEz1/5DPOH9lXt16OQ8N1fwdlH5dubl+0TgX2UKg13Knpon6MB/zMlMWg5Vg57rS8wE46yiyBRMbjCqLwhefSCwqlDOW13K/h6W6ogugTxUyX4i4rgpC9ZqRiFNTw=
